services:
  chemist:
    container_name: chemist
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      neo4j:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: wget -q -O /dev/null http://chemist:8080/health || exit 1
      interval: 2s
      timeout: 15s
      retries: 10
      start_period: 15s

  neo4j:
    container_name: neo4j
    image: neo4j:4.1
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    environment:
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=6G
      - NEO4J_dbms_memory_transaction_max__size=6G
      - NEO4J_dbms_security_procedures_default__allowed=true
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    user: "${NEO4J_UID:?error}:${NEO4J_GID:?error}"
    healthcheck:
      test: wget -q -O /dev/null http://localhost:7474 || exit 1
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 1s

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      neo4j:
        condition: service_healthy
    entrypoint: [ "sh", "-c", "/scripts/migrate.sh" ]
    environment:
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_BOLT_PORT=${NEO4J_BOLT_PORT}
      - NEO4J_HTTP_PORT=${NEO4J_HTTP_PORT}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_HOST=${NEO4J_HOST}
