# version: '3.9'

services:
  biocad:
    container_name: biocad
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080 || exit 1
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      # - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    user: "${NEO4J_UID:?error}:${NEO4J_GID:?error}"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 1s
