name: Haskell CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"
      - "**/*.sh"
      - "examples/**"
      - "migrations/**"
      - "scripts/**"
      - "Dockerfile*"
      - "docker*"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"
      - "**/*.sh"
      - "examples/**"
      - "migrations/**"
      - "scripts/**"
      - "Dockerfile*"
      - "docker*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.6"

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal install hspec-discover --overwrite-policy=always
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Run tests
        run: cabal test all --test-show-details=always

      - name: Build documentation
        run: |
          cabal update
          cabal haddock --haddock-for-hackage --haddock-hyperlink-source --enable-doc
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CHEMIST_DOC }}
          publish_dir: ./dist-newstyle/build/<arch>/<ghc-version>/doc/html/<package-name>
  
